# Generated by Django 5.0.6 on 2024-08-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.orderitem'),
        ),
    ]
