# Generated by Django 5.0.6 on 2025-04-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
