# Generated by Django 5.0.6 on 2025-04-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_sent_by_remove_supportticket_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_by_id',
            new_name='sent_by',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='user_id',
            new_name='user',
        ),
    ]
